//! View bridges — ALICE-View ↔ DB, CDN, Cache, Analytics
//!
//! 7 bridges connecting the rendering/viewport layer to the ALICE ecosystem.
//! Covers view telemetry persistence, CDN-based asset delivery, cached render
//! state, and analytics feed from frame timing data.

#[inline(always)]
fn fnv1a(data: &[u8]) -> u64 {
    let mut h: u64 = 0xcbf29ce484222325;
    for &b in data { h ^= b as u64; h = h.wrapping_mul(0x100000001b3); }
    h
}

// ── Bridge 1: View → DB (frame telemetry persistence) ───────────────────

/// Frame telemetry record for ALICE-DB persistence.
///
/// One record per rendered frame.  `content_hash` is derived from frame
/// index and timing values so duplicate submissions are detectable without
/// storing raw timestamps.
pub struct ViewDbFrameRecord {
    /// FNV-1a hash over frame_index ++ frame_ms bytes.
    pub content_hash: u64,
    /// Sequential frame index within the session.
    pub frame_index: u64,
    /// Frame render time in milliseconds.
    pub frame_ms: f32,
    /// Triangle count rendered in this frame.
    pub triangle_count: u32,
    /// Draw call count for this frame.
    pub draw_calls: u32,
    /// Whether the frame missed its deadline (frame_ms > budget_ms).
    pub is_dropped: bool,
}

/// Serialize a rendered-frame event for ALICE-DB persistence.
///
/// `budget_ms` is the target frame budget (e.g. 16.67 for 60 Hz).
/// `is_dropped` is set branchlessly when `frame_ms > budget_ms`.
#[inline]
pub fn view_to_db_frame_record(
    frame_index: u64,
    frame_ms: f32,
    triangle_count: u32,
    draw_calls: u32,
    budget_ms: f32,
) -> ViewDbFrameRecord {
    let mut data = [0u8; 12];
    data[0..8].copy_from_slice(&frame_index.to_le_bytes());
    data[8..12].copy_from_slice(&frame_ms.to_bits().to_le_bytes());
    let content_hash = fnv1a(&data);
    // Branchless: compiler emits fcmp + csel / cmov.
    let is_dropped = frame_ms > budget_ms;
    ViewDbFrameRecord {
        content_hash,
        frame_index,
        frame_ms,
        triangle_count,
        draw_calls,
        is_dropped,
    }
}

// ── Bridge 2: View → CDN (asset fetch request) ──────────────────────────

/// CDN asset-fetch request generated by the view layer.
///
/// The view layer issues this when a texture, mesh, or shader asset is not
/// present in the local render cache and must be fetched from the CDN.
pub struct ViewCdnAssetRequest {
    /// FNV-1a hash of the asset URI — CDN routing key.
    pub asset_hash: u64,
    /// Byte length of the asset URI string.
    pub uri_bytes: usize,
    /// Asset type tag: 0=texture, 1=mesh, 2=shader, 3=animation, 4=audio.
    pub asset_type: u8,
    /// Preferred maximum delivery latency in milliseconds.
    pub deadline_ms: u32,
    /// Priority tier: 0=background, 1=normal, 2=urgent.
    pub priority: u8,
}

/// Build a CDN asset-fetch request from the view layer.
///
/// Priority is derived branchlessly from `asset_type`:
/// - shader (2) → 2 (urgent: blocks rendering without it)
/// - texture (0) or mesh (1) → 1 (normal)
/// - animation (3) or audio (4) → 0 (background)
#[inline]
pub fn view_to_cdn_asset_request(
    asset_uri: &str,
    asset_type: u8,
    deadline_ms: u32,
) -> ViewCdnAssetRequest {
    let asset_hash = fnv1a(asset_uri.as_bytes());
    // Branchless priority from asset_type.
    let is_shader = (asset_type == 2) as u8;
    let is_render_critical = ((asset_type == 0) | (asset_type == 1)) as u8;
    let priority = is_shader.wrapping_mul(2) | (is_render_critical & !is_shader);
    ViewCdnAssetRequest {
        asset_hash,
        uri_bytes: asset_uri.len(),
        asset_type,
        deadline_ms,
        priority,
    }
}

// ── Bridge 3: View → Cache (render state caching) ────────────────────────

/// Cached render state entry for ALICE-Cache.
///
/// Stores a lightweight fingerprint of the GPU pipeline state so that
/// identical draw submissions can reuse a compiled pipeline object from cache
/// without re-issuing expensive driver-level compilations.
pub struct ViewCacheRenderState {
    /// FNV-1a hash of pipeline state bytes — cache key.
    pub pipeline_hash: u64,
    /// Shader variant identifier.
    pub shader_variant: u32,
    /// Blend mode (0=opaque, 1=alpha-blend, 2=additive, 3=multiply).
    pub blend_mode: u8,
    /// Cull mode (0=none, 1=back, 2=front).
    pub cull_mode: u8,
    /// Estimated pipeline compilation cost in microseconds.
    pub compile_cost_us: u32,
    /// Whether depth write is enabled.
    pub depth_write: bool,
}

/// Build a render state cache entry for ALICE-Cache.
///
/// `compile_cost_us` is estimated from blend_mode and shader_variant:
/// transparent blends are more expensive due to order-dependent compositing.
#[inline]
pub fn view_to_cache_render_state(
    shader_variant: u32,
    blend_mode: u8,
    cull_mode: u8,
    depth_write: bool,
) -> ViewCacheRenderState {
    let mut data = [0u8; 7];
    data[0..4].copy_from_slice(&shader_variant.to_le_bytes());
    data[4] = blend_mode;
    data[5] = cull_mode;
    data[6] = depth_write as u8;
    let pipeline_hash = fnv1a(&data);
    // Transparent modes cost ~2x more to compile (alpha-blend, additive, multiply).
    let is_transparent = (blend_mode > 0) as u32;
    let compile_cost_us = 500u32.wrapping_add(is_transparent.wrapping_mul(500));
    ViewCacheRenderState {
        pipeline_hash,
        shader_variant,
        blend_mode,
        cull_mode,
        compile_cost_us,
        depth_write,
    }
}

// ── Bridge 4: View → Analytics (frame timing metrics) ────────────────────

/// Frame timing metrics for ALICE-Analytics ingestion.
///
/// Aggregates per-frame data into analytics-friendly statistics so that
/// the analytics layer can build latency histograms and detect GPU stalls.
pub struct ViewAnalyticsFrameMetrics {
    /// FNV-1a hash of session_id bytes — analytics stream key.
    pub session_hash: u64,
    /// Mean frame time over the sample window, in milliseconds.
    pub mean_frame_ms: f32,
    /// Minimum frame time in the window.
    pub min_frame_ms: f32,
    /// Maximum frame time in the window.
    pub max_frame_ms: f32,
    /// Frames per second (branchless reciprocal: 1000 / mean_frame_ms).
    pub fps_estimate: f32,
    /// Drop rate in permille (dropped frames * 1000 / total frames).
    pub drop_rate_permille: u32,
    /// Total frames in the sample window.
    pub frame_count: usize,
}

/// Aggregate frame timing data for ALICE-Analytics.
///
/// `frame_ms_samples` is a slice of raw per-frame render times.
/// `budget_ms` is the target deadline (16.67 for 60 Hz, 33.33 for 30 Hz).
/// `session_id` is an opaque string identifier for the render session.
#[inline]
pub fn view_to_analytics_frame_metrics(
    session_id: &str,
    frame_ms_samples: &[f32],
    budget_ms: f32,
) -> ViewAnalyticsFrameMetrics {
    let session_hash = fnv1a(session_id.as_bytes());
    let frame_count = frame_ms_samples.len();

    // Single-pass statistics — no heap allocation.
    let (min_ms, max_ms, sum_ms, dropped) = frame_ms_samples.iter().fold(
        (f32::MAX, 0.0f32, 0.0f32, 0u32),
        |(mn, mx, s, d), &t| (
            mn.min(t),
            mx.max(t),
            s + t,
            d + (t > budget_ms) as u32,
        ),
    );

    let count_safe = (frame_count as f32).max(1.0);
    let mean_frame_ms = sum_ms / count_safe;

    // Branchless FPS: reciprocal multiply avoids branch on mean == 0.
    // Clamp mean to 0.1 ms floor to avoid inf.
    let mean_clamped = mean_frame_ms.max(0.1);
    let fps_estimate = 1000.0 / mean_clamped;

    // Drop rate in permille (branchless).
    let total_safe = (frame_count as u32).max(1);
    let drop_rate_permille = dropped.wrapping_mul(1_000) / total_safe;

    // Clamp sentinel min to 0.0 when no samples (f32::MAX → 0.0).
    let min_frame_ms = if frame_count == 0 { 0.0 } else { min_ms };

    ViewAnalyticsFrameMetrics {
        session_hash,
        mean_frame_ms,
        min_frame_ms,
        max_frame_ms: max_ms,
        fps_estimate,
        drop_rate_permille,
        frame_count,
    }
}

// ── Bridge 5: View → DB (viewport config persistence) ────────────────────

/// Viewport configuration record for ALICE-DB.
///
/// Persists the current camera and viewport parameters so sessions can be
/// restored without re-transmitting the full scene graph.
pub struct ViewDbViewportConfig {
    /// FNV-1a hash of width ++ height ++ fov bytes — change key.
    pub config_hash: u64,
    /// Viewport width in pixels.
    pub width: u32,
    /// Viewport height in pixels.
    pub height: u32,
    /// Vertical field-of-view in degrees.
    pub fov_degrees: f32,
    /// Near clip plane distance.
    pub near_clip: f32,
    /// Far clip plane distance.
    pub far_clip: f32,
    /// MSAA sample count (1, 2, 4, 8).
    pub msaa_samples: u8,
}

/// Persist viewport configuration for ALICE-DB.
#[inline]
pub fn view_to_db_viewport_config(
    width: u32,
    height: u32,
    fov_degrees: f32,
    near_clip: f32,
    far_clip: f32,
    msaa_samples: u8,
) -> ViewDbViewportConfig {
    let mut data = [0u8; 21];
    data[0..4].copy_from_slice(&width.to_le_bytes());
    data[4..8].copy_from_slice(&height.to_le_bytes());
    data[8..12].copy_from_slice(&fov_degrees.to_bits().to_le_bytes());
    data[12..16].copy_from_slice(&near_clip.to_bits().to_le_bytes());
    data[16..20].copy_from_slice(&far_clip.to_bits().to_le_bytes());
    data[20] = msaa_samples;
    let config_hash = fnv1a(&data);
    ViewDbViewportConfig {
        config_hash,
        width,
        height,
        fov_degrees,
        near_clip,
        far_clip,
        msaa_samples,
    }
}

// ── Bridge 6: View → Cache (texture cache entry) ─────────────────────────

/// Texture cache entry for ALICE-Cache.
///
/// Derived from the texture's content hash and GPU format metadata so that
/// the cache layer can evict entries with mismatched format versions.
pub struct ViewCacheTextureEntry {
    /// FNV-1a hash of texture bytes — primary cache key.
    pub texture_hash: u64,
    /// Texture width in pixels.
    pub width: u32,
    /// Texture height in pixels.
    pub height: u32,
    /// GPU pixel format tag (0=RGBA8, 1=BC7, 2=ASTC4x4, 3=R16F).
    pub format: u8,
    /// Mipmap level count.
    pub mip_levels: u8,
    /// GPU memory footprint in bytes.
    pub gpu_bytes: usize,
}

/// Build a texture cache entry for ALICE-Cache.
///
/// `gpu_bytes` is computed as `width * height * bpp * mip_factor` where
/// `bpp` depends on format (branchless lookup table).
#[inline]
pub fn view_to_cache_texture_entry(
    texture_data: &[u8],
    width: u32,
    height: u32,
    format: u8,
    mip_levels: u8,
) -> ViewCacheTextureEntry {
    let texture_hash = fnv1a(texture_data);
    // Bytes-per-pixel lookup (branchless): RGBA8=4, BC7=1 (block compressed ~1Bpp),
    // ASTC4x4=1, R16F=2.  Index clamped to table size.
    const BPP_TABLE: [usize; 4] = [4, 1, 1, 2];
    let fmt_idx = (format as usize).min(3);
    let bpp = BPP_TABLE[fmt_idx];
    // Mipmap overhead: sum of geometric series ≈ 1.33x for full mip chain.
    // Approximate as (mip_levels as usize) * 4 / 3 (branchless integer mul+div).
    let mip_factor = (mip_levels as usize).max(1);
    let gpu_bytes = width as usize * height as usize * bpp * mip_factor * 4 / 3;
    ViewCacheTextureEntry {
        texture_hash,
        width,
        height,
        format,
        mip_levels,
        gpu_bytes,
    }
}

// ── Bridge 7: View → CDN (LOD prefetch request) ──────────────────────────

/// Level-of-detail prefetch request for ALICE-CDN.
///
/// Issued when the view layer predicts that the camera will approach a mesh
/// cluster requiring a higher-fidelity LOD level within `lookahead_ms`.
pub struct ViewCdnLodPrefetch {
    /// FNV-1a hash of mesh_id bytes — CDN routing key.
    pub mesh_hash: u64,
    /// Target LOD level to prefetch (0=highest detail, 4=lowest).
    pub lod_level: u8,
    /// Estimated time until the LOD is needed, in milliseconds.
    pub lookahead_ms: u32,
    /// Predicted GPU memory required for the LOD, in bytes.
    pub gpu_bytes: usize,
    /// MIME type for CDN content negotiation.
    pub content_type: &'static str,
}

/// Build a LOD prefetch request for ALICE-CDN.
#[inline]
pub fn view_to_cdn_lod_prefetch(
    mesh_id: &str,
    lod_level: u8,
    lookahead_ms: u32,
    gpu_bytes: usize,
) -> ViewCdnLodPrefetch {
    let mesh_hash = fnv1a(mesh_id.as_bytes());
    ViewCdnLodPrefetch {
        mesh_hash,
        lod_level: lod_level.min(4),
        lookahead_ms,
        gpu_bytes,
        content_type: "application/x-alice-mesh",
    }
}

// ── Tests ────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_view_to_db_frame_record_on_time() {
        let rec = view_to_db_frame_record(0, 10.0, 50_000, 200, 16.67);
        assert_ne!(rec.content_hash, 0);
        assert_eq!(rec.frame_index, 0);
        assert!((rec.frame_ms - 10.0).abs() < f32::EPSILON);
        assert_eq!(rec.triangle_count, 50_000);
        assert_eq!(rec.draw_calls, 200);
        assert!(!rec.is_dropped, "10ms frame should not be dropped at 16.67ms budget");
    }

    #[test]
    fn test_view_to_db_frame_record_dropped() {
        let rec = view_to_db_frame_record(1, 33.5, 80_000, 300, 16.67);
        assert!(rec.is_dropped, "33.5ms frame should be dropped at 16.67ms budget");
    }

    #[test]
    fn test_view_to_cdn_asset_request_shader_urgent() {
        let req = view_to_cdn_asset_request("shaders/pbr.spv", 2, 5);
        assert_ne!(req.asset_hash, 0);
        assert_eq!(req.asset_type, 2);
        assert_eq!(req.priority, 2, "shader must be urgent priority");
        assert_eq!(req.deadline_ms, 5);
    }

    #[test]
    fn test_view_to_cdn_asset_request_texture_normal() {
        let req = view_to_cdn_asset_request("textures/rock_albedo.ktx2", 0, 100);
        assert_eq!(req.priority, 1, "texture must be normal priority");
    }

    #[test]
    fn test_view_to_cdn_asset_request_audio_background() {
        let req = view_to_cdn_asset_request("audio/ambient.ogg", 4, 5000);
        assert_eq!(req.priority, 0, "audio must be background priority");
    }

    #[test]
    fn test_view_to_cache_render_state_opaque() {
        let state = view_to_cache_render_state(42, 0, 1, true);
        assert_ne!(state.pipeline_hash, 0);
        assert_eq!(state.blend_mode, 0);
        assert_eq!(state.compile_cost_us, 500, "opaque blend has base cost");
        assert!(state.depth_write);
    }

    #[test]
    fn test_view_to_cache_render_state_transparent_costs_more() {
        let opaque = view_to_cache_render_state(1, 0, 1, true);
        let transparent = view_to_cache_render_state(1, 1, 1, false);
        assert!(transparent.compile_cost_us > opaque.compile_cost_us);
        // Different blend mode → different hash.
        assert_ne!(opaque.pipeline_hash, transparent.pipeline_hash);
    }

    #[test]
    fn test_view_to_analytics_frame_metrics_basic() {
        let samples = [10.0f32, 12.0, 11.0, 25.0, 9.0]; // 1 dropped at 16.67ms budget
        let m = view_to_analytics_frame_metrics("session-001", &samples, 16.67);
        assert_ne!(m.session_hash, 0);
        assert_eq!(m.frame_count, 5);
        assert!(m.fps_estimate > 0.0);
        assert!(m.min_frame_ms < m.max_frame_ms);
        // 1 drop out of 5 = 200 permille.
        assert_eq!(m.drop_rate_permille, 200);
    }

    #[test]
    fn test_view_to_analytics_frame_metrics_empty() {
        let m = view_to_analytics_frame_metrics("session-empty", &[], 16.67);
        assert_eq!(m.frame_count, 0);
        assert_eq!(m.min_frame_ms, 0.0);
        assert_eq!(m.drop_rate_permille, 0);
    }

    #[test]
    fn test_view_to_db_viewport_config() {
        let cfg = view_to_db_viewport_config(1920, 1080, 60.0, 0.1, 10_000.0, 4);
        assert_ne!(cfg.config_hash, 0);
        assert_eq!(cfg.width, 1920);
        assert_eq!(cfg.height, 1080);
        assert_eq!(cfg.msaa_samples, 4);
        // Different width → different hash.
        let cfg2 = view_to_db_viewport_config(1280, 720, 60.0, 0.1, 10_000.0, 4);
        assert_ne!(cfg.config_hash, cfg2.config_hash);
    }

    #[test]
    fn test_view_to_cache_texture_entry() {
        let data = vec![0u8; 1024];
        let entry = view_to_cache_texture_entry(&data, 512, 512, 0, 4);
        assert_ne!(entry.texture_hash, 0);
        assert_eq!(entry.width, 512);
        assert_eq!(entry.height, 512);
        assert_eq!(entry.format, 0);
        assert!(entry.gpu_bytes > 0);
    }

    #[test]
    fn test_view_to_cdn_lod_prefetch() {
        let req = view_to_cdn_lod_prefetch("meshes/city_block.alm", 2, 500, 4 * 1024 * 1024);
        assert_ne!(req.mesh_hash, 0);
        assert_eq!(req.lod_level, 2);
        assert_eq!(req.lookahead_ms, 500);
        assert_eq!(req.content_type, "application/x-alice-mesh");
        // lod_level clamped to 4 max.
        let clamped = view_to_cdn_lod_prefetch("meshes/test.alm", 99, 100, 0);
        assert_eq!(clamped.lod_level, 4);
    }
}
