//! LLM extended bridges — ALICE-LLM ↔ Edge, SIMD, Streaming-Protocol, Voice, Speculative
//!
//! 5 bridges connecting LLM inference to edge deployment, SIMD acceleration,
//! token streaming, voice synthesis, and dual-model speculative decoding.

#[inline(always)]
fn fnv1a(data: &[u8]) -> u64 {
    let mut h: u64 = 0xcbf2_9ce4_8422_2325;
    for &b in data {
        h ^= b as u64;
        h = h.wrapping_mul(0x0100_0000_01b3);
    }
    h
}

// ── Bridge 1: LLM → Edge (edge inference deployment) ────────────────────

/// Edge deployment descriptor for an LLM model.
pub struct LlmEdgeDeployment {
    /// Content hash over the deployment descriptor.
    pub content_hash: u64,
    /// Model size in bytes.
    pub model_size_bytes: u64,
    /// Number of model layers.
    pub num_layers: u32,
    /// Hidden dimension size.
    pub hidden_dim: u32,
    /// Quantization type (0=F32, 1=Q8_0, 2=Q4_K, 3=Q6_K).
    pub quant_type: u8,
    /// Estimated tokens per second on edge device.
    pub estimated_tps: f32,
    /// Whether the model fits in device memory.
    pub fits_in_memory: bool,
}

/// Build an edge deployment descriptor from model metadata.
///
/// Memory check: model_size_bytes must be below device_memory_bytes to deploy.
#[inline]
#[must_use]
pub fn llm_to_edge_deployment(
    model_size_bytes: u64,
    num_layers: u32,
    hidden_dim: u32,
    quant_type: u8,
    device_memory_bytes: u64,
    device_bandwidth_gbps: f32,
) -> LlmEdgeDeployment {
    let mut buf = [0u8; 21];
    buf[0..8].copy_from_slice(&model_size_bytes.to_le_bytes());
    buf[8..12].copy_from_slice(&num_layers.to_le_bytes());
    buf[12..16].copy_from_slice(&hidden_dim.to_le_bytes());
    buf[16..20].copy_from_slice(&device_bandwidth_gbps.to_bits().to_le_bytes());
    buf[20] = quant_type;
    let fits_in_memory = model_size_bytes < device_memory_bytes;
    // Bandwidth-limited estimate: model_bytes / bandwidth = seconds/token
    let secs_per_token = model_size_bytes as f64 / (device_bandwidth_gbps as f64 * 1e9);
    let estimated_tps = if secs_per_token > 0.0 {
        (1.0 / secs_per_token) as f32
    } else {
        0.0
    };
    LlmEdgeDeployment {
        content_hash: fnv1a(&buf),
        model_size_bytes,
        num_layers,
        hidden_dim,
        quant_type,
        estimated_tps,
        fits_in_memory,
    }
}

// ── Bridge 2: LLM → SIMD (vectorization metadata) ──────────────────────

/// SIMD acceleration metadata for LLM matvec kernels.
pub struct LlmSimdProfile {
    /// Content hash over the SIMD profile.
    pub content_hash: u64,
    /// Number of SDOT instructions generated by LLVM auto-vectorization.
    pub sdot_count: u32,
    /// Quantization dot product type (0=Q4_K×Q8_K, 1=Q6_K×Q8_K, 2=F32).
    pub dot_type: u8,
    /// Whether target-cpu=native is enabled.
    pub native_cpu: bool,
    /// Effective SIMD width in bytes (16 for NEON 128-bit).
    pub simd_width_bytes: u8,
    /// Matvec throughput in GFLOPS.
    pub throughput_gflops: f32,
}

/// Build a SIMD acceleration profile for LLM matvec kernels.
#[inline]
#[must_use]
pub fn llm_to_simd_profile(
    sdot_count: u32,
    dot_type: u8,
    native_cpu: bool,
    simd_width_bytes: u8,
    throughput_gflops: f32,
) -> LlmSimdProfile {
    let mut buf = [0u8; 11];
    buf[0..4].copy_from_slice(&sdot_count.to_le_bytes());
    buf[4] = dot_type;
    buf[5] = native_cpu as u8;
    buf[6] = simd_width_bytes;
    buf[7..11].copy_from_slice(&throughput_gflops.to_bits().to_le_bytes());
    LlmSimdProfile {
        content_hash: fnv1a(&buf),
        sdot_count,
        dot_type,
        native_cpu,
        simd_width_bytes,
        throughput_gflops,
    }
}

// ── Bridge 3: LLM → Streaming-Protocol (token streaming) ───────────────

/// Token streaming packet for ALICE-Streaming-Protocol.
pub struct LlmStreamPacket {
    /// Content hash over the packet payload.
    pub content_hash: u64,
    /// Token ID generated.
    pub token_id: u32,
    /// Sequence position in the generation.
    pub seq_pos: u32,
    /// Whether this is the final token (EOS).
    pub is_eos: bool,
    /// Decode latency for this token in microseconds.
    pub decode_us: u32,
    /// Log-probability of the chosen token.
    pub log_prob: f32,
}

/// Build a streaming packet from a single generated token.
#[inline]
#[must_use]
pub fn llm_to_stream_packet(
    token_id: u32,
    seq_pos: u32,
    is_eos: bool,
    decode_us: u32,
    log_prob: f32,
) -> LlmStreamPacket {
    let mut buf = [0u8; 17];
    buf[0..4].copy_from_slice(&token_id.to_le_bytes());
    buf[4..8].copy_from_slice(&seq_pos.to_le_bytes());
    buf[8] = is_eos as u8;
    buf[9..13].copy_from_slice(&decode_us.to_le_bytes());
    buf[13..17].copy_from_slice(&log_prob.to_bits().to_le_bytes());
    LlmStreamPacket {
        content_hash: fnv1a(&buf),
        token_id,
        seq_pos,
        is_eos,
        decode_us,
        log_prob,
    }
}

// ── Bridge 4: LLM → Voice (text-to-speech pipeline) ────────────────────

/// Voice synthesis request from LLM-generated text.
pub struct LlmVoiceRequest {
    /// Content hash over the voice request.
    pub content_hash: u64,
    /// Number of text characters to synthesize.
    pub text_len: u32,
    /// Target sample rate in Hz.
    pub sample_rate: u32,
    /// Estimated audio duration in milliseconds.
    pub estimated_duration_ms: u32,
    /// Language identifier hash.
    pub lang_hash: u64,
    /// Whether streaming TTS is requested.
    pub streaming: bool,
}

/// Build a voice synthesis request from LLM output text.
///
/// Duration estimate: ~80 ms per character (average speech rate ~150 wpm).
#[inline]
#[must_use]
pub fn llm_to_voice_request(
    text_len: u32,
    sample_rate: u32,
    lang_hash: u64,
    streaming: bool,
) -> LlmVoiceRequest {
    let mut buf = [0u8; 17];
    buf[0..4].copy_from_slice(&text_len.to_le_bytes());
    buf[4..8].copy_from_slice(&sample_rate.to_le_bytes());
    buf[8..16].copy_from_slice(&lang_hash.to_le_bytes());
    buf[16] = streaming as u8;
    // ~80 ms per character at average speech rate
    let estimated_duration_ms = text_len * 80;
    LlmVoiceRequest {
        content_hash: fnv1a(&buf),
        text_len,
        sample_rate,
        estimated_duration_ms,
        lang_hash,
        streaming,
    }
}

// ── Bridge 5: LLM → Edge (speculative decoding config) ─────────────────

/// Dual-model speculative decoding configuration for edge deployment.
pub struct LlmSpeculativeConfig {
    /// Content hash over the speculative config.
    pub content_hash: u64,
    /// Draft model layers.
    pub draft_layers: u32,
    /// Verifier model layers.
    pub verify_layers: u32,
    /// Speculation depth K.
    pub spec_k: u8,
    /// Accept rate from last run (0.0–1.0).
    pub accept_rate: f32,
    /// Draft model size in bytes.
    pub draft_size_bytes: u64,
    /// Size ratio (verifier / draft).
    pub size_ratio: f32,
}

/// Build a speculative decoding config from dual-model parameters.
#[inline]
#[must_use]
pub fn llm_to_speculative_config(
    draft_layers: u32,
    verify_layers: u32,
    spec_k: u8,
    accept_rate: f32,
    draft_size_bytes: u64,
    verify_size_bytes: u64,
) -> LlmSpeculativeConfig {
    let mut buf = [0u8; 17];
    buf[0..4].copy_from_slice(&draft_layers.to_le_bytes());
    buf[4..8].copy_from_slice(&verify_layers.to_le_bytes());
    buf[8] = spec_k;
    buf[9..17].copy_from_slice(&draft_size_bytes.to_le_bytes());
    let size_ratio = if draft_size_bytes > 0 {
        verify_size_bytes as f32 / draft_size_bytes as f32
    } else {
        0.0
    };
    LlmSpeculativeConfig {
        content_hash: fnv1a(&buf),
        draft_layers,
        verify_layers,
        spec_k,
        accept_rate,
        draft_size_bytes,
        size_ratio,
    }
}

// ── Tests ────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_edge_deployment_fits() {
        let dep = llm_to_edge_deployment(770_000_000, 16, 2048, 2, 8_000_000_000, 34.0);
        assert_ne!(dep.content_hash, 0);
        assert!(dep.fits_in_memory);
        assert_eq!(dep.num_layers, 16);
        assert_eq!(dep.quant_type, 2);
        assert!(dep.estimated_tps > 0.0);
    }

    #[test]
    fn test_edge_deployment_no_fit() {
        let dep = llm_to_edge_deployment(10_000_000_000, 32, 4096, 2, 8_000_000_000, 91.0);
        assert!(!dep.fits_in_memory);
    }

    #[test]
    fn test_simd_profile_native() {
        let prof = llm_to_simd_profile(37, 0, true, 16, 12.5);
        assert_ne!(prof.content_hash, 0);
        assert_eq!(prof.sdot_count, 37);
        assert!(prof.native_cpu);
        assert_eq!(prof.simd_width_bytes, 16);
    }

    #[test]
    fn test_simd_profile_hash_determinism() {
        let a = llm_to_simd_profile(37, 0, true, 16, 12.5);
        let b = llm_to_simd_profile(37, 0, true, 16, 12.5);
        assert_eq!(a.content_hash, b.content_hash);
    }

    #[test]
    fn test_stream_packet_normal() {
        let pkt = llm_to_stream_packet(16309, 0, false, 500, -0.5);
        assert_ne!(pkt.content_hash, 0);
        assert_eq!(pkt.token_id, 16309);
        assert!(!pkt.is_eos);
    }

    #[test]
    fn test_stream_packet_eos() {
        let pkt = llm_to_stream_packet(128009, 7, true, 200, -1.2);
        assert!(pkt.is_eos);
        assert_eq!(pkt.seq_pos, 7);
    }

    #[test]
    fn test_voice_request_duration() {
        let req = llm_to_voice_request(100, 24000, 0xaabb, true);
        assert_ne!(req.content_hash, 0);
        assert_eq!(req.estimated_duration_ms, 8000); // 100 chars * 80 ms
        assert!(req.streaming);
        assert_eq!(req.sample_rate, 24000);
    }

    #[test]
    fn test_speculative_config_ratio() {
        // 1B draft (770MB) → 8B verify (5GB)
        let cfg = llm_to_speculative_config(16, 32, 4, 0.63, 770_000_000, 5_000_000_000);
        assert_ne!(cfg.content_hash, 0);
        assert_eq!(cfg.draft_layers, 16);
        assert_eq!(cfg.verify_layers, 32);
        assert_eq!(cfg.spec_k, 4);
        assert!((cfg.accept_rate - 0.63).abs() < 0.01);
        assert!((cfg.size_ratio - 6.49).abs() < 0.1);
    }

    #[test]
    fn test_speculative_config_hash_determinism() {
        let a = llm_to_speculative_config(16, 32, 4, 0.63, 770_000_000, 5_000_000_000);
        let b = llm_to_speculative_config(16, 32, 4, 0.63, 770_000_000, 5_000_000_000);
        assert_eq!(a.content_hash, b.content_hash);
    }
}
